export const StoredBookingDatas = [{
    'booking_status': 'saved',
    'pickup_location_details': 'Alangayam',
    'drop_location_details': 'Alwarkurichi',
    'pickup_location_contact': '9845164700',
    'drop_location_contact': '7459364700',
    'transit_insurance': true,
    'gps_tracking': false,
    'scheduled_date': '30-6-2017',
    'vehicle_type': 'Tata 407',
    'vehicle_size': '9.10 X 6.2 X 6.2',
    'vehicle_tonnage': 2.5,
    'vehicle_goods': 'Cotton seed',
    'delivery_status': 'n/a',
    'booking_id': 'n/a',
    'expected_delivery': 'n/a'
  },
  {
    'booking_status': 'saved',
    'pickup_location_details': 'Mallasamudram',
    'drop_location_details': 'Alwarkurichi',
    'pickup_location_contact': '9845164700',
    'drop_location_contact': '7459364700',
    'transit_insurance': true,
    'gps_tracking': false,
    'scheduled_date': '28-6-2017',
    'vehicle_type': 'Open Truck',
    'vehicle_size': '18 X 7 X 8',
    'vehicle_tonnage': 9,
    'vehicle_goods': 'Cotton seed',
    'delivery_status': 'n/a',
    'booking_id': 'n/a',
    'expected_delivery': 'n/a'
  },
  {
    'booking_status': 'completed',
    'pickup_location_details': 'Chennai',
    'drop_location_details': 'Madurai',
    'pickup_location_contact': '8459262922',
    'drop_location_contact': '8459262922',
    'transit_insurance': false,
    'gps_tracking': true,
    'scheduled_date': '12-12-2016',
    'vehicle_type': 'Semi Low Bed Trailer',
    'vehicle_size': '40 X 8 X 8.6',
    'vehicle_tonnage': 20,
    'vehicle_goods': 'House Hold Goods',
    'delivery_status': 'delivered',
    'booking_id': Math.random().toString(36).slice(2),
    'expected_delivery': 'n/a'
  },
  {
    'booking_status': 'completed',
    'pickup_location_details': 'Pondicherry',
    'drop_location_details': 'Chennai',
    'pickup_location_contact': '8459262922',
    'drop_location_contact': '8459262922',
    'transit_insurance': false,
    'gps_tracking': true,
    'scheduled_date': '1-10-2016',
    'vehicle_type': 'Triple excel',
    'vehicle_size': '40 X 8 X 8.6',
    'vehicle_tonnage': 20,
    'vehicle_goods': 'House Hold Goods',
    'delivery_status': 'delivered',
    'booking_id': Math.random().toString(36).slice(2),
    'expected_delivery': 'n/a'
  },
  {
    'booking_status': 'completed',
    'pickup_location_details': 'Madurai',
    'drop_location_details': 'Trichy',
    'pickup_location_contact': '8459262922',
    'drop_location_contact': '8459262922',
    'transit_insurance': false,
    'gps_tracking': true,
    'scheduled_date': '12-12-2016',
    'vehicle_type': 'Touras',
    'vehicle_size': '40 X 8 X 8.6',
    'vehicle_tonnage': 20,
    'vehicle_goods': 'House Hold Goods',
    'delivery_status': 'delivered',
    'booking_id': Math.random().toString(36).slice(2),
    'expected_delivery': 'n/a'
  },
  {
    'booking_status': 'completed',
    'pickup_location_details': 'Minjur',
    'drop_location_details': 'Kaniyakumari',
    'pickup_location_contact': '8459262922',
    'drop_location_contact': '8459262922',
    'transit_insurance': false,
    'gps_tracking': true,
    'scheduled_date': '12-12-2016',
    'vehicle_type': 'Truck',
    'vehicle_size': '18 X7 X 6.5',
    'vehicle_tonnage': 9,
    'vehicle_goods': 'Rice or wheet or Agriculture Products',
    'delivery_status': 'delivered',
    'booking_id': Math.random().toString(36).slice(2),
    'expected_delivery': 'n/a'
  },
  {
    'booking_status': 'active',
    'pickup_location_details': 'Alampalayam',
    'drop_location_details': 'Thevaram',
    'pickup_location_contact': '8251815109',
    'drop_location_contact': '9638521410',
    'transit_insurance': true,
    'gps_tracking': true,
    'scheduled_date': '10-12-2017',
    'vehicle_type': 'Open Truck',
    'vehicle_size': '18 X 7 X 8',
    'vehicle_tonnage': 9,
    'vehicle_goods': 'Packed Food',
    'delivery_status': 'Yet to Start',
    'booking_id': Math.random().toString(36).slice(2),
    'expected_delivery': '16-12-2017'
  },
  {
    'booking_status': 'active',
    'pickup_location_details': 'Thiagadurgam',
    'drop_location_details': 'Chennai',
    'pickup_location_contact': '8251815109',
    'drop_location_contact': '9638521410',
    'transit_insurance': true,
    'gps_tracking': true,
    'scheduled_date': '19-12-2017',
    'vehicle_type': 'Open Truck',
    'vehicle_size': '18 X 7 X 8',
    'vehicle_tonnage': 9,
    'vehicle_goods': 'Packed Food',
    'delivery_status': 'In Progress',
    'booking_id': Math.random().toString(36).slice(2),
    'expected_delivery': '28-12-2017'
  },
  {
    'booking_status': 'active',
    'pickup_location_details': 'Chennai',
    'drop_location_details': 'Trichy',
    'pickup_location_contact': '8251815109',
    'drop_location_contact': '9638521410',
    'transit_insurance': true,
    'gps_tracking': true,
    'scheduled_date': '28-11-2017',
    'vehicle_type': 'Open Truck',
    'vehicle_size': '18 X 7 X 8',
    'vehicle_tonnage': 9,
    'vehicle_goods': 'Packed Food',
    'delivery_status': 'In progress',
    'booking_id': Math.random().toString(36).slice(2),
    'expected_delivery': '1-12-2017'
  }
];
